### ISSUE TITLE
[umbrella] Implement level-triggered architecture

### ISSUE THREAD

**Issue by squaremo** [weaveworks/pipeline-controller#193]
Implement the level-triggered architecture as explained in https://github.com/weaveworks/weave-gitops-private/blob/191-pipelines-watcher/docs/rfcs/0006-pipelines-level-triggered/README.md.

This gives a chunking of the implementation, so that each bit doesn't take too long, and some things can be done concurrently. In particular, the prototype implementation of the first issue below gives a base for reimplementing promotions, and can be extended to support remote clusters independently.

First:

 - [x] weaveworks/pipeline-controller#194

Then, to some extent concurrently:

 - [x] weaveworks/pipeline-controller#195
 - [x] weaveworks/pipeline-controller#196
 - [ ] weaveworks/pipeline-controller#197  (needs weaveworks/pipeline-controller#195)
 - [ ] weaveworks/weave-gitops-enterprise#3637 (do in tandem with UI updates)
 - [ ] weaveworks/pipeline-controller#199 (needs weaveworks/pipeline-controller#197)
