### ISSUE TITLE
Pipelines 0.3 - Ability to create a pipeline through the WGE GUI

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/pipeline-controller#39]
This Epic is to cover the work required to deliver capabilities describe in this [initiative](https://www.notion.so/weaveworks/Pipeline-creation-through-GUI-and-Templates-d0cb922e339740d3821d490ba8dcc4b5)

Specifically, the ability to create a new Pipeline from within the Weave GitOps Enterprise GUI. This is an important capability as we look to round out an end to end experience for working with Pipelines and being able to easily demonstrate how the product supports you through that process.

Acceptance Criteria
- [x] As a user I can navigate to the Pipelines view and click "Create Pipeline" to be taken to the Templates view
- [x] As a user I can make use of a reference template supporting a tenant isolation by **namespace** strategy to associate a HelmRelease application to a Pipeline 
- [x] As a user I can make use of a reference template supporting a tenant isolation by **cluster** strategy to associate a HelmRelease application to a Pipeline 
- [x] As a user I can make use of a reference template to establish the required flux resources on a leaf cluster to enable promotion via Pipelines
- [x] Pipeline templates have been validated by CX and agreed that the templates support their existing demos
- [ ] Public documentation exists to describe the templates and common edits i.e. adding an additional environment
- [x] Public documentation exists to support the create Pipeline UX through the GUI
- [ ] Sales demos are updated to show the creation of a Pipeline for an application

Designs: https://www.figma.com/file/IVHnM9iyeFWpd11evtY8ux/Weave-GitOps?node-id=4717%3A5709
